<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add a new user</name>
   <tag></tag>
   <elementGuidId>d46a5d46-7bc9-4b90-9b6f-52875a1d8750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='WorkerIndex']/div[2]/div/div/div[2]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.new_staff_link.new-user-btn-set</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79628343-27e1-4eb2-bdf1-f4384c7bcaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary new_staff_link new-user-btn-set</value>
      <webElementGuid>9e1c4045-c1f2-4b95-8acd-f332118ac209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New Form</value>
      <webElementGuid>38f626e8-beaf-4634-a599-26e5a5623626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5a74fc67-fb7f-4777-a8ae-115e5fa7198c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#NewStaffForm</value>
      <webElementGuid>923ceda8-4631-4a71-931f-4fd3d3ed9ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-remote</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a13b2783-417d-44c8-9ce9-1396922fb027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/staff/new</value>
      <webElementGuid>02f1ec01-4c2f-4dc5-834a-a3ae897cd417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                           Add a new user 
</value>
      <webElementGuid>c0aec7bf-a9f2-40e7-85f5-f5a670ac6730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WorkerIndex&quot;)/div[@class=&quot;col-xs-12 col-sm-9 col-md-9 col-lg-10&quot;]/div[@class=&quot;RightContent staff-right-content&quot;]/div[@class=&quot;SWrapper&quot;]/div[@class=&quot;#&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-8 col-lg-9&quot;]/a[@class=&quot;btn btn-primary new_staff_link new-user-btn-set&quot;]</value>
      <webElementGuid>e3014be4-757e-4d09-8fdf-bd63512f6c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WorkerIndex']/div[2]/div/div/div[2]/div/div[2]/a</value>
      <webElementGuid>9c25cc88-6530-4503-9f29-218d13e0ccb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL Users'])[1]/following::a[1]</value>
      <webElementGuid>7d5f1c72-3f0a-40dc-bc08-3a1faf1dc19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupons'])[2]/following::a[1]</value>
      <webElementGuid>c0abe196-dba8-40a1-8fa7-7d1715d8f574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::a[1]</value>
      <webElementGuid>c9876c93-e999-43fc-8969-ef1c0ad4c32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add a new user']/parent::*</value>
      <webElementGuid>93ea9f6a-7eae-4285-a455-6f63ebac41dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/staff/new')]</value>
      <webElementGuid>c932d663-fdaf-418b-9891-995dd6e4d6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>fb63501a-b378-4e49-b90b-f6443e17e260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'New Form' and @href = '/staff/new' and (text() = '
                           Add a new user 
' or . = '
                           Add a new user 
')]</value>
      <webElementGuid>5b70aa2b-f514-49f7-8fa6-23c094e0fb33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
