<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Users</name>
   <tag></tag>
   <elementGuidId>85193e18-2bf9-4ef7-af5e-0ed2b636946f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftMenu']/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.accordion-toggle.staff_class</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>af11f5a9-e167-4021-81c0-dd6ad27292d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-toggle staff_class</value>
      <webElementGuid>5d51a65e-0c89-4aff-99fe-618b78f8f707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/staff</value>
      <webElementGuid>c60eccdc-c45c-4afd-a627-a84600924dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-turbolinks</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c3236534-ba18-49a8-ac28-a5606d74caec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
             Users
          </value>
      <webElementGuid>7ec2bb9d-f5f5-49d7-86cf-446d493f20e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftMenu&quot;)/div[@class=&quot;accordion-group&quot;]/div[@class=&quot;accordion-heading&quot;]/a[@class=&quot;accordion-toggle staff_class&quot;]</value>
      <webElementGuid>a5d7b622-0a74-4adb-991a-6ca5ec0fedf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftMenu']/div[2]/div/a</value>
      <webElementGuid>d1b327ce-5b48-46f7-bf2a-99e02d841f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::a[2]</value>
      <webElementGuid>290289b9-5c17-4dcb-83e5-1fa9b3853258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is one'])[1]/preceding::a[2]</value>
      <webElementGuid>ac3d1902-d717-482e-9bb0-7a15c83c00c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/staff')])[2]</value>
      <webElementGuid>fc8dbb21-94d1-485e-b2d0-2bf5954557c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>c0379c61-aab7-4a88-b885-0f02cefcddfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/staff' and (text() = '
             Users
          ' or . = '
             Users
          ')]</value>
      <webElementGuid>e18f975a-5756-4e81-9135-59a8422a93c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
