<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_workeruser_attributesemail</name>
   <tag></tag>
   <elementGuidId>4437a94d-0c9d-405e-98a6-49c856f31d59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='worker_user_attributes_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#worker_user_attributes_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23d893d3-343f-4f3f-b59a-2c53bf8fb759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>0cdf6f86-1cd1-4b90-a1ce-d6f8191611bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ee709bf-9d1b-4683-99ec-238c5718b4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>worker[user_attributes][email]</value>
      <webElementGuid>3d96956a-e20c-4cbb-9d46-57d6ed58f693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>worker_user_attributes_email</value>
      <webElementGuid>f134b86b-2ccd-4939-9485-16300529d847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;worker_user_attributes_email&quot;)</value>
      <webElementGuid>5b90675d-2a8f-4ebe-a0e8-c8de2da8462b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='worker_user_attributes_email']</value>
      <webElementGuid>c7ae1088-fc6f-4a6f-aecc-37b53c3d547f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='redNew']/div/div/div/div[4]/div[2]/input</value>
      <webElementGuid>f349c75c-913a-43e1-aa09-3942b24ed301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>72b8e796-32fa-42a3-9663-476ccfecd14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @type = 'text' and @name = 'worker[user_attributes][email]' and @id = 'worker_user_attributes_email']</value>
      <webElementGuid>77d5e19b-bb93-41c8-871c-878543fdf70d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
