<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Users</name>
   <tag></tag>
   <elementGuidId>2f6d575f-2ff5-4040-82e7-035dd32be8bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftMenu']/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.accordion-toggle.staff_class</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07a5960a-ba3d-4b67-8df8-8b9b1484a97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-toggle staff_class</value>
      <webElementGuid>a3905feb-a7f3-4c1d-8618-8cd495bd6a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/staff</value>
      <webElementGuid>404c6b7d-2c84-4aaf-94bd-708f353a7cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-turbolinks</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5b1a704a-71c5-4570-b007-6d48d5d2bf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
             Users
          </value>
      <webElementGuid>ea59e092-c0fe-4aa1-b5db-7acafafbc50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftMenu&quot;)/div[@class=&quot;accordion-group&quot;]/div[@class=&quot;accordion-heading&quot;]/a[@class=&quot;accordion-toggle staff_class&quot;]</value>
      <webElementGuid>2de0aed1-ac44-4cad-9e7a-05d1246fc002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftMenu']/div[2]/div/a</value>
      <webElementGuid>77ff5239-7578-42cc-932a-fa909d624a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::a[2]</value>
      <webElementGuid>57c14def-9cde-4fab-8fde-04c1f77e5fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is one'])[1]/preceding::a[2]</value>
      <webElementGuid>20c212e2-6289-4588-b89f-fb6122425e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/staff')])[2]</value>
      <webElementGuid>05949af6-5506-4851-8dbc-f996eac22ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>c345951a-b160-4034-b722-d90f631ffb58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/staff' and (text() = '
             Users
          ' or . = '
             Users
          ')]</value>
      <webElementGuid>b2e381b8-fdc8-4787-9dfa-aaf46244b5bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
