<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_workeruser_attributesmob_7fa4d0</name>
   <tag></tag>
   <elementGuidId>1cd2b1fb-ef0a-4520-8b04-445adf7c932b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='worker_user_attributes_mobile_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#worker_user_attributes_mobile_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8912b385-96f3-4529-8c77-182006d6c015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Business Phone</value>
      <webElementGuid>ba02f1bc-8ba8-4690-8f32-f4efb840e646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>84bcd9ed-1221-420e-a4ee-60cb74284740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>worker[user_attributes][mobile_number]</value>
      <webElementGuid>c1b2d2fa-e1ec-46c0-bf9b-5e70ebd87fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>worker_user_attributes_mobile_number</value>
      <webElementGuid>571b0183-435e-4aac-a9ca-85f54f02254e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0bcf35fe-6959-4b9d-a204-9c8c0f05071c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0301 2345678</value>
      <webElementGuid>2214869b-d917-420a-954a-a7a13d07b329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;worker_user_attributes_mobile_number&quot;)</value>
      <webElementGuid>8269df1a-541c-4149-920f-4632448a398a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='worker_user_attributes_mobile_number']</value>
      <webElementGuid>0d199d37-0b32-4867-a589-d49df484b90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='redEdit']/div/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>9c7baedd-c0c3-45a4-9b1e-c4342a6b3d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>31ec6576-2b61-4005-a810-d501f7b3d1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'worker[user_attributes][mobile_number]' and @id = 'worker_user_attributes_mobile_number' and @placeholder = '0301 2345678']</value>
      <webElementGuid>fde789ec-dd9c-4aff-a498-6ccdba792b51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
